### PR TITLE
Fix for release build failure during single thread execution

### PR DESCRIPTION
**Pull request by ashishk-1**
This is related to #1739 
Fixes the issue for release build failure.
```
CXX(target) out/Release/obj.target/instaweb_spriter/net/instaweb/spriter/libpng_image_library.o
In file included from ./net/instaweb/spriter/libpng_image_library.h:32:0,
                 from net/instaweb/spriter/libpng_image_library.cc:20:
./third_party/libpng/src/png.h:361:27: fatal error: pnglibconf.h: No such file or directory
 #   include "pnglibconf.h"
                           ^
compilation terminated.
```

### CODE REVIEW

**Review by oschaaf — APPROVED** [review]

**Comment by eldk** [comment]
Same error with Ubuntu 16.04.4 LTS and mod_pagespeed https://github.com/apache/incubator-pagespeed-mod/commit/74b6395074c8a08f9f3d1e2722c9a9ffcd49659d

**Comment by oschaaf** [comment]
Whoops. I'll see if I can fix that. I suspect this was introduced in 7ea8d5fc141c7067c54ffa2b9fbc552c15089ca6.

**Comment by eldk** [comment]
Hello,

If I build with at least -j2  : 
```
make -j2 BUILDTYPE=Debug mod_pagespeed_test pagespeed_automatic_test
```
Build is OK.

Thanks,

Eric
